################################################################
# Name: fairy_tale_origin_link.R
# Purpose: Joining fairy books stories to their
# country of origin and AT number
# Creator: N. M. Shahir
# Github: nmshahir
# Data source: University of Missouri Libraries
# https://libraryguides.missouri.edu/c.php?g=1078942&p=7861219
# Data Obtained: 2026.03.10
#################################################################
install.packages(
  "datapasta",
  repos = c(mm = "https://milesmcbain.r-universe.dev", getOption("repos"))
)
library(datapasta)
library(dplyr)
library(tidyverse)

red_fairy_origins <- tibble::tribble(
  ~Tale                                , ~AT                 , ~Culture       ,
  "Black Thief and Knight of Glen"     , "NA"                , "Irish"        ,
  "Brother and Sister"                 , "450"               , "German"       ,
  "Bushy Bride"                        , "403"               , "Norwegian"    ,
  "Dapplegrim"                         , "NA"                , "Norwegian"    ,
  "Death of Koshchei thee Deathless"   , "552"               , "Slavic"       ,
  "Drakestail"                         , "715"               , "French"       ,
  "Enchanted Canary"                   , "NA"                , "French"       ,
  "Enchanted Pig"                      , "425A"              , "Romanian"     ,
  "Farmer WeatherBeard"                , "325"               , "Norwegian"    ,
  "Golden Branch"                      , "NA"                , "French"       ,
  "Golden Goose"                       , "571"               , "German"       ,
  "Graciosa and Percinet"              , "NA"                , "French"       ,
  "Jack and the Beanstalk"             , "328"               , "Unattributed" ,
  "Kari Woodengown"                    , "510A"              , "Norwegian"    ,
  "Little Good Mouse"                  , "NA"                , "French"       ,
  "Marvellous Musician"                , "151"               , "German"       ,
  "Minnikin"                           , "NA"                , "Norwegian"    ,
  "Mother Holle"                       , "480"               , "German"       ,
  "Nettle Spinner"                     , "NA"                , "French"       ,
  "Norka"                              , "301"               , "Unattributed" ,
  "Princess Mayblossom"                , "NA"                , "French"       ,
  "Princess Rosette"                   , "NA"                , "French"       ,
  "Rapunzel"                           , "310"               , "German"       ,
  "Ratcatcher"                         , "570*"              , "French"       ,
  "Seven Foals"                        , "NA"                , "Norwegian"    ,
  "Six Sillies"                        , "1229*, 1384, 1450" , "Belgian?"     ,
  "Snowdrop"                           , "709"               , "German"       ,
  "Soria Moria Castle"                 , "NA"                , "Norwegian"    ,
  "Story of Sigurd"                    , "NA"                , "Icelandic"    ,
  "The Master Thief"                   , "1525A"             , "Norwegian"    ,
  "Three Dwarfs"                       , "403B"              , "German"       ,
  "Three Princesses of Whiteland"      , "NA"                , "Norwegian"    ,
  "True History of Little Golden Hood" , "333"               , "French"       ,
  "Twelve Brothers"                    , "451"               , "German"       ,
  "Twelve Dancing Princesses"          , "306"               , "Unattributed" ,
  "Voice of Death"                     , "NA"                , "Romanian"     ,
  "Wonderful Birch"                    , "NA"                , "Russian"
)

crimson_fairy_origins <- tibble::tribble(
  ~Tale                                         , ~AT                       , ~Country       ,
  "Boy Who Could Keep a Secret"                 , "NA"                      , "Hungarian"    ,
  "Clever Maria"                                , "NA"                      , "Portuguese"   ,
  "Colony of Cats"                              , "NA"                      , "Unattributed" ,
  "Cottager and His Cat"                        , "1651"                    , "Icelandic"    ,
  "Crab and Money"                              , "NA"                      , "Japanese"     ,
  "Death of Abu Nowas and of his Wife"          , "NA"                      , "African"      ,
  "Eisenkopf"                                   , "NA"                      , "Hungarian"    ,
  "Gifts of the Magician"                       , "NA"                      , "Finnish"      ,
  "Gold-Bearded Man"                            , "502"                     , "Hungarian"    ,
  "Hairy Man"                                   , "502"                     , "Russiann"     ,
  "Horse Gullfaxi and Sword Gunnfoder"          , "NA"                      , "Icelandic"    ,
  "How the Beggar Turned into Count Piro"       , "545B"                    , "Italian"      ,
  "How the Wicked Tanuki was Punished"          , "NA"                      , "Japanese"     ,
  "How to Find Out a True Friend"               , "NA"                      , "Italian"      ,
  "Language of Beasts"                          , "670"                     , "Unattributed" ,
  "Little Wildrose"                             , "NA"                      , "Romanian"     ,
  "Lovely Ilonka"                               , "408"                     , "Hungarian"    ,
  "Lucky Luck"                                  , "460B"                    , "Hungarian"    ,
  "Magic Kettle"                                , "NA"                      , "Japanese"     ,
  "Motiratika"                                  , "NA"                      , "African"      ,
  "Niels and the Giants"                        , "304"                     , "Unattributed" ,
  "Paperarelloo"                                , "314"                     , "Italian"      ,
  "Prince and Dragon"                           , "302"                     , "Serbian"      ,
  "Prince Who Would Seek Immortality"           , "NA"                      , "Hungarian"    ,
  "Rogues and Herdsman"                         , "NA"                      , "Icelandic"    ,
  "Shepherd Paul"                               , "301"                     , "Hungarian"    ,
  "Six Hungry Beasts"                           , "20, 20B, 37, 56A, 1310C" , "Finnish"      ,
  "Stone-Cutter"                                , "555"                     , "Japanese"     ,
  "Story of Seven Simons"                       , "513B"                    , "Hungarian"    ,
  "Story of the Sham Prince or Ambitous Tailor" , "NA"                      , "Unattributed" ,
  "Strong Prince"                               , "590"                     , "Hungarian"    ,
  "Three Robes"                                 , "403"                     , "Icelandic"    ,
  "Tiidu The Piper"                             , "566"                     , "Estonian"     ,
  "To Your Good Health!"                        , "858"                     , "Russiann"     ,
  "Treasure Seeker"                             , "NA"                      , "Unattributed" ,
  "Tritill, Litill, and the Birds"              , "401A"                    , "Hungarian"
)

green_fairy_origins <- tibble::tribble(
  ~Tale                                                    , ~AT    , ~Country       ,
  NA                                                       , NA     , " "            ,
  "Allerleiraugh, or the Many-Furred Creature"             , "510B" , "German"       ,
  "Biter Bit"                                              , "1539" , "European"     ,
  "Blue Bird"                                              , "432"  , "French"       ,
  "Crystal Coffin"                                         , "410"  , "German"       ,
  "Dirty Shepherdess"                                      , "510"  , "French"       ,
  "Enchanted Ring"                                         , "560"  , "French"       ,
  "Enchanted Snake"                                        , "425A" , "Unattributed" ,
  "Enchanted Watch"                                        , "560"  , "French"       ,
  "Fairy Gifts"                                            , "NA"   , "French"       ,
  "Golden Blackbird"                                       , "550"  , "French"       ,
  "Golden Lads"                                            , "555"  , "German"       ,
  "Golden Mermaid"                                         , "550"  , "German"       ,
  "Half-Chick"                                             , "715"  , "Spanish"      ,
  "Heart of Ice"                                           , "NA"   , "French"       ,
  "Jack My Hedgehog"                                       , "441"  , "German"       ,
  "Jorinde and Joringel"                                   , "405"  , "German"       ,
  "King Kojata"                                            , "313"  , "Russiann"     ,
  "Little One-Eye, Little Two-Eyes, and Little Three-Eyes" , "511"  , "German"       ,
  "Little Soldier"                                         , "NA"   , "French"       ,
  "Magic Swan"                                             , "571"  , "European"     ,
  "Prince Featherhead and the Princess Celandine"          , "NA"   , "French"       ,
  "Prince Fickle and Fair Helena"                          , "NA"   , "German"       ,
  "Prince Narcissus and the Princess Potentilla"           , "NA"   , "French"       ,
  "Prince Vivien and the Princess Placida"                 , "NA"   , "French"       ,
  "Puddocky"                                               , "402"  , "German"       ,
  "Riddle"                                                 , "851"  , "German"       ,
  "Rosanella"                                              , "NA"   , "French"       ,
  "Snuff-Box"                                              , "560"  , "French"       ,
  "Spindel Shuttle and Needle"                             , "585"  , "German"       ,
  "Story of a Clever Tailor"                               , "850"  , "German"       ,
  "Story of Caliph Stork"                                  , "NA"   , "Unattributed" ,
  "Story of Hok Lee and the Dwarfs"                        , "NA"   , "Chinese"      ,
  "Story of the Fisherman and his Wife"                    , "555"  , "German"       ,
  "Story of the Three Bears"                               , "171"  , "English"      ,
  "Sylvain and Jocosa"                                     , "NA"   , "French"       ,
  "Three Dogs"                                             , "300"  , "German"       ,
  "Three Little Pigs"                                      , "124"  , "Unattributed" ,
  "Three Musicians"                                        , "NA"   , "German"       ,
  "Three Snake-Leaves"                                     , "NA"   , "German"       ,
  "Twelve Huntsmen"                                        , "884"  , "German"       ,
  "War of Wolf and Fox"                                    , "NA"   , "German"       ,
  "White Snake"                                            , "673"  , "German"
)

grey_fairy_origins <- tibble::tribble(
  ~Tale                                              , ~AT                      , ~Country       ,
  NA                                                 , NA                       , " "            ,
  "Bear"                                             , "510B"                   , "Unattributed" ,
  "Bobino"                                           , "671"                    , "Unattributed" ,
  "Cannetella"                                       , "900"                    , "Italian"      ,
  "Daughter of Buk Ettemsuch"                        , "405A*"                  , "African"      ,
  "Dog and Sparrow"                                  , "58"                     , "German"       ,
  "Donkey Skin"                                      , "510B"                   , "French"       ,
  "Fairy's Blunder"                                  , "NA"                     , "French"       ,
  "Fortunatus and his Purse"                         , "566"                    , "Unattributed" ,
  "Goat-Faced Girl"                                  , "900A"                   , "Italian"      ,
  "Goblin Ponty"                                     , "NA"                     , "French"       ,
  "Herr Lazarus and the Draken"                      , "1049, 1115, 1149, 1640" , "Unattributed" ,
  "Impossible Enchantment"                           , "NA"                     , "Unattributed" ,
  "Jackal and Spring"                                , "55"                     , "African"      ,
  "Janni and the Draken"                             , "300"                    , "Unattributed" ,
  "Laughing Eye and Weeping Eye, of the Limping Fox" , "NA"                     , "Slavic"       ,
  "Little Gray Man"                                  , "301"                    , "German"       ,
  "Long, Broad, and Quickeye"                        , "513"                    , "Slavic"       ,
  "Magician's Horse"                                 , "314"                    , "Unattributed" ,
  "Mohammed with the Magic Finger"                   , "NA"                     , "African"      ,
  "Ogre"                                             , "563"                    , "Italian"      ,
  "Partnership of Thief and Liar"                    , "1654"                   , "Unattributed" ,
  "Prunella"                                         , "310"                    , "Unattributed" ,
  "Simpleton"                                        , "513"                    , "Italian"      ,
  "Story of Bensurdatu"                              , "301"                    , "Italian"      ,
  "Story of Dschemil and Dschemila"                  , "313"                    , "African"      ,
  "Story of Fair Circassians"                        , "NA"                     , "French"       ,
  "Story of the Queen of the Flowery Isles"          , "NA"                     , "French"       ,
  "Story of the Three Sons of Hali"                  , "NA"                     , "Unattributed" ,
  "Street Musicians"                                 , "130"                    , "German"       ,
  "Sunchild"                                         , "898"                    , "Unattributed" ,
  "Twin Brothers"                                    , "303"                    , "Unattributed" ,
  "Udea and Her Seven Brothers"                      , "451"                    , "African"      ,
  "Unlooked-for-Prince"                              , "313"                    , "Slavic"       ,
  "What Came of Picking Flowers"                     , "552"                    , "Portuguese"   ,
  "White Wolf"                                       , "425A"                   , "Unattributed"
)

lilac_fairy_origins <- tibble::tribble(
  ~Tale                            , ~AT     , ~Country       ,
  NA                               , NA      , " "            ,
  "Battle of Birds"                , "NA"    , "Scottish"     ,
  "BelievingHusbands"              , "1406"  , "Scottish"     ,
  "Bones of Djulung"               , "NA"    , "Unattributed" ,
  "Brown Bear of Norway"           , "425A"  , "Scottish"     ,
  "Brownie of the Lake"            , "NA"    , "French"       ,
  "Castle of Kerglas"              , "NA"    , "French"       ,
  "Enchanted Deer"                 , "NA"    , "Scottish"     ,
  "Escape of Mouse"                , "NA"    , "Welsh"        ,
  "Fairy Nurse"                    , "476*"  , "Irish"        ,
  "False Prince and True"          , "NA"    , "Portuguese"   ,
  "Fish Story"                     , "NA"    , "Oceania"      ,
  "Four Gifts"                     , "NA"    , "French"       ,
  "French Puck"                    , "NA"    , "French"       ,
  "Groac'h of Isle of Lok"         , "NA"    , "French"       ,
  "Heart of a Monkey"              , "91"    , "African"      ,
  "Hoodie-Crow"                    , "425A"  , "Scottish"     ,
  "How Brave Walter Hunter Wolves" , "NA"    , "Finnish"      ,
  "Jogi's Punishment"              , "NA"    , "Indian"       ,
  "King of Waterfalls"             , "NA"    , "Scottish"     ,
  "Lady of Fountain"               , "NA"    , "Welsh"        ,
  "Little Lasse"                   , "700"   , "Finnish"      ,
  "Lost Paradise"                  , "NA"    , "French"       ,
  "Moti'"                          , "NA"    , "Pushto"       ,
  "One-Handed Girl"                , "706"   , "African"      ,
  "Raspberry Worm"                 , "NA"    , "Finnish"      ,
  "Rich Brother and Poor Brother"  , "1534"  , "Portuguese"   ,
  "Sea King's Gift"                , "NA"    , "Finnish"      ,
  "Shifty Lad"                     , "1525D" , "Scottish"     ,
  "Stones of Plouhinec"            , "NA"    , "French"       ,
  "Story of a Very Bad Boy"        , "1539"  , "French"       ,
  "Three Crowns"                   , "NA"    , "Scottish"     ,
  "Winning of Olwen"               , "NA"    , "Welsh"        ,
  "Wonderful Tune"                 , "NA"    , "Irish"
)

olive_fairy_origins <- tibble::tribble(
  ~Tale                                   , ~AT    , ~Country       ,
  "Billy Goat and the King"               , "670"  , "Indian"       ,
  "Blue Parrot"                           , "NA"   , "French"       ,
  "Boy Who Found Fear at Last"            , "326"  , "Turkish"      ,
  "Clever Weaver"                         , "NA"   , "Armenian"     ,
  "Comb and the Collar"                   , "NA"   , "English"      ,
  "Diamond Cut Diamond"                   , "NA"   , "Indian"       ,
  "Dorani"                                , "NA"   , "Indian"       ,
  "Fate of the Turtle"                    , "225A" , "Indian"       ,
  "Five Wise Words of the Guru"           , "NA"   , "Indian"       ,
  "Geirlug the King's Daughter"           , "NA"   , "Icelandic"    ,
  "Golden-Headed Fish"                    , "551"  , "Armenian"     ,
  "Grasp All Lose All"                    , "776"  , "Indian"       ,
  "Green Knight"                          , "510"  , "Danish"       ,
  "He Wins Who Waits"                     , "NA"   , "Armenian"     ,
  "Jackal or Tiger?"                      , "NA"   , "Unattributed" ,
  "Kupti and Imani"                       , "NA"   , "Indian"       ,
  "Long-Bow Story"                        , "1920" , "Indian"       ,
  "Madschun"                              , "577"  , "Turkish"      ,
  "Prince and the Princess in the Forest" , "NA"   , "Danish"       ,
  "Punishment of the Fairy Gangana"       , "NA"   , "French"       ,
  "Samba the Coward"                      , "NA"   , "African"      ,
  "Satin Surgeon"                         , "NA"   , "French"       ,
  "Silent Princess"                       , "898"  , "Turkish"      ,
  "Snake Prince"                          , "425A" , "Indian"       ,
  "Steel Cane"                            , "779"  , "Armenian"     ,
  "Story of Little King Loc"              , "NA"   , "French"       ,
  "Story of Zoulvisia"                    , "NA"   , "Armenian"     ,
  "Strange Adventures of Little Maia"     , "700"  , "Unattributed" ,
  "Thanksgiving of the Wazir"             , "NA"   , "Indian"
)

orange_fairy_origins <- tibble::tribble(
  ~Tale                                      , ~AT      , ~Country          ,
  "Adventures of a Jackal"                   , "NA"     , "African"         ,
  "Adventures of a Jackal's Eldest Son"      , "NA"     , "African"         ,
  "Adventures of an Indian Brave"            , "NA"     , "Native American" ,
  "Adventures of Covan Brown-Haired"         , "NA"     , "Irish"           ,
  "Adventures of the Younger Son of Jackal"  , "NA"     , "African"         ,
  "Andras Baive"                             , "NA"     , "Lapp"            ,
  "Bird of Truth"                            , "707"    , "Spanish"         ,
  "Clever Cat"                               , "NA"     , "African"         ,
  "Enchanted Wreath"                         , "480"    , "Scandinavian"    ,
  "Foolish Weaver"                           , "1693"   , "Pushto"          ,
  "Fox and Wolf"                             , "32, 34" , "Spanish"         ,
  "Frog and Lion Fairy"                      , "NA"     , "French"          ,
  "Girl-Fish"                                , "NA"     , "Catalan"         ,
  "Goldsmith's Fortune"                      , "NA"     , "Pathan"          ,
  "How Ian Direach Got the Blue Falcon"      , "NA"     , "Scottish"        ,
  "How Isuro the Rabbit Tricked Gudu"        , "NA"     , "African"         ,
  "How the Stalos Were Tricked"              , "328"    , "Lapp"            ,
  "Ian The Soldier's Son"                    , "NA"     , "Scottish"        ,
  "Magic Book"                               , "325"    , "Danish"          ,
  "Magic Mirror"                             , "NA"     , "African"         ,
  "Mink and Wolf"                            , "NA"     , "Native American" ,
  "Owl and Eagle"                            , "NA"     , "Native American" ,
  "Pinkel the Thief"                         , "NA"     , "Scandinavian"    ,
  "Princess Bella-Flor"                      , "NA"     , "Spanish"         ,
  "Rover of Plain"                           , "NA"     , "African"         ,
  "Story of Manus"                           , "NA"     , "Scottish"        ,
  "Story of the Hero Makoma from Senna"      , "NA"     , "African"         ,
  "Story of the King Who Would See Paradise" , "NA"     , "Pathan"          ,
  "Three Treasures of Giants"                , "569"    , "Slavic"          ,
  "Two Caskets"                              , "480"    , "Scandinavian"    ,
  "Ugly Duckling"                            , "NA"     , "Danish"          ,
  "White Doe"                                , "898"    , "French"          ,
  "White Slipper"                            , "NA"     , "Spanish"
)

pink_fairy_origins <- tibble::tribble(
  ~Tale                                              , ~AT               , ~Country       ,
  "Bird 'Grip'"                                      , "550"             , "Swedish"      ,
  "Catherine and Her Destiny"                        , "938"             , "Italian"      ,
  "Cat's Elopement"                                  , "NA"              , "Japanese"     ,
  "Cunning Shoemaker"                                , "1539"            , "Italian"      ,
  "Don Giovanni de la Fortuna"                       , "361"             , "Italian"      ,
  "Esben and the Witch"                              , "327B, 328, 1121" , "Danish"       ,
  "Fir-Tree"                                         , "NA"              , "Danish"       ,
  "Flying Trunk"                                     , "NA"              , "Danish"       ,
  "Goblin and Grocer"                                , "NA"              , "Danish"       ,
  "Golden Lion"                                      , "860A*"           , "Italian"      ,
  "Hans the Mermaid's Son"                           , "NA"              , "Danish"       ,
  "House in the Wood"                                , "431"             , "German"       ,
  "How the Dragon Was Tricked"                       , "328"             , "Greek"        ,
  "How the Hermit Helped to Win the King's Daughter" , "NA"              , "Italian"      ,
  "I Know What I have Learned"                       , "NA"              , "Danish"       ,
  "The Jackal, Dove and Panther"                     , "56"              , "African"      ,
  "King Lindorm"                                     , "433B"            , "Swedish."     ,
  "King Who Would have a Beautiful Wife"             , "NA"              , "Italian"      ,
  "Little Hare"                                      , "NA"              , "African"      ,
  "Maiden Bright-Eye"                                , "480"             , "Danish"       ,
  "Man without a Heart"                              , "303A"            , "Unattributed" ,
  "Master and Pupil"                                 , "325"             , "Danish"       ,
  "Merry Wifes"                                      , "1406"            , "Danish"       ,
  "Peter Bull"                                       , "1675"            , "Danish"       ,
  "Princess in the Chest"                            , "307"             , "Danish"       ,
  "Princess Minion-Minette"                          , "NA"              , "French"       ,
  "Shirt-Collar"                                     , "NA"              , "Danish"       ,
  "Slaying of Tanuki"                                , "NA"              , "Japanese"     ,
  "Snow Man"                                         , "NA"              , "Danish"       ,
  "Snowflake"                                        , "703*"            , "Slavic"       ,
  "Snow-Queen"                                       , "NA"              , "Danish"       ,
  "Sparrow with Slit Tongue"                         , "480"             , "Japanese"     ,
  "Sprig of Rosemary"                                , "425A"            , "Catalan"      ,
  "Story of Ciccu"                                   , "569"             , "Italian"      ,
  "Three Brothers"                                   , "301"             , "German"       ,
  "Troll's Daughter"                                 , "302"             , "Danish"       ,
  "Two Brothers"                                     , "303"             , "Italian"      ,
  "Uraschimataro and the Turtle"                     , "681"             , "Japanese"     ,
  "Water of Life"                                    , "707"             , "Catalan"      ,
  "White Dove"                                       , "313"             , "Danish"       ,
  "Wounded Lion"                                     , "444*"            , "Catalan"
)

violet_fairy_origins <- tibble::tribble(
  ~Tale                                                , ~AT                            , ~Country       ,
  NA                                                   , NA                             , " "            ,
  "Boys with Golden Stars"                             , "707"                          , "Romanian"     ,
  "Child Who Came from an Egg"                         , "NA"                           , "Estonian"     ,
  "Enchanted Knife"                                    , "576"                          , "Serbian"      ,
  "Envious Neighbor"                                   , "NA"                           , "Japanese"     ,
  "Fairy of Dawn"                                      , "551"                          , "Romanian"     ,
  "Finest Liar in the World"                           , "1920"                         , "Serbian"      ,
  "Frog"                                               , "402"                          , "Italian"      ,
  "Girl Who Pretended to be a Boy"                     , "884B"                         , "Romanian"     ,
  "Goat's Ears of the Emperor Trojan"                  , "NA"                           , "Serbian"      ,
  "Grateful Prince"                                    , "313"                          , "Estonian"     ,
  "Headless Dwarfs"                                    , "326"                          , "Estonian"     ,
  "History of Dwarf Long Nose"                         , "NA"                           , "Unattributed" ,
  "How a Fish Swam in the Air and a Hare in the Water" , "NA"                           , "Unattributed" ,
  "Jesper Who Herded the Hares"                        , "570"                          , "Scandinavian" ,
  "Lute Player"                                        , "888"                          , "Russiann"     ,
  "Maiden with Wooden Helmet"                          , "NA"                           , "Japanese"     ,
  "Mogarzea and His Son"                               , "NA"                           , "Unattributed" ,
  "Monkey and Jelly-Fish"                              , "NA"                           , "Japanese"     ,
  "Nine Pea-Hens and Golden Apples"                    , "400"                          , "Serbian"      ,
  "Nunda, Eater of People"                             , "550"                          , "African"      ,
  "Prince Who Wanted to See the World"                 , "313"                          , "Portuguese"   ,
  "Princess Who was Hidden Underground"                , "870"                          , "German"       ,
  "Schippeitaro"                                       , "300"                          , "Japanese"     ,
  "Stan Bolovan"                                       , "1049, 1060, 1063, 1115, 1149" , "Romanian"     ,
  "Story of a Gazelle"                                 , "545B"                         , "African"      ,
  "Story of Halfman"                                   , "122F, 1119, 1121"             , "African"      ,
  "Story of Hassebu"                                   , "NA"                           , "African"      ,
  "Story of Three Wonderful Beggars"                   , "461"                          , "Serbian"      ,
  "A Tale of the Tontlawald"                           , "NA"                           , "Estonian"     ,
  "Three Princes and Their Beasts"                     , "NA"                           , "Lithuanian"   ,
  "Two Frogs"                                          , "NA"                           , "Japanese"     ,
  "Two in a Sack"                                      , "NA"                           , "Russiann"     ,
  "Underground Workers"                                , "NA"                           , "Estonian"     ,
  "Virgilius the Sorcerer"                             , "331"                          , "Unattributed" ,
  "Young Man Who Would have his Eyes Opened"           , "NA"                           , "Estonian"
)

yellow_fairy_origins <- tibble::tribble(
  ~Tale                                          , ~AT    , ~Country          ,
  NA                                             , NA     , " "               ,
  "Alphege or the Green Monkey"                  , "NA"   , "Unattributed"    ,
  "Blockhead-Hans"                               , "853"  , "Unattributed"    ,
  "Blue Mountains"                               , "301A" , "Unattributed"    ,
  "Boy and Wolves or Broken Promise"             , "NA"   , "Native American" ,
  "Cat and Mouse in Partnership"                 , "15"   , "Unattributed"    ,
  "Crow"                                         , "425N" , "Polish"          ,
  "Dead Wife"                                    , "NA"   , "Native American" ,
  "Death of Sun-Hero"                            , "NA"   , "Bukovina"        ,
  "Donkey Cabbage"                               , "566"  , "Unattributed"    ,
  "Dragon and His Grandmother"                   , "812"  , "Unattributed"    ,
  "Dragon of the North"                          , "300"  , "Estonian"        ,
  "Fairer-Than-A-Fairy"                          , "NA"   , "Unattributed"    ,
  "Flower Queen's Dauther"                       , "300"  , "Bukovina"        ,
  "Flying Ship"                                  , "513B" , "Russiann"        ,
  "Giants and Herd-Boy"                          , "NA"   , "Bukovina"        ,
  "Glass Axe"                                    , "313"  , "Hungarian"       ,
  "Glass Mountain"                               , "530"  , "Polish"          ,
  "Golden Crab"                                  , "425D" , "Greek"           ,
  "Grateful Beasts"                              , "613"  , "Hungarian"       ,
  "Hazel-Nut Child"                              , "700"  , "Bukovina"        ,
  "Hermod and Hadvor R"                          , "NA"   , "Icelandic"       ,
  "How Six Men Travelled Through the Wide World" , "NA"   , "Unattributed"    ,
  "How to Tell a True Princess"                  , "704"  , "Unattributed"    ,
  "In The Land of Souls"                         , "NA"   , "Native American" ,
  "Invisible Prince"                             , "NA"   , "Unattributed"    ,
  "Iron Stove"                                   , "425A" , "German"          ,
  "Little Green Frog"                            , "550"  , "French"          ,
  "Magic Ring"                                   , "560"  , "Unattributed"    ,
  "Nightengale"                                  , "NA"   , "Unattributed"    ,
  "Nixy"                                         , "316"  , "German"          ,
  "Prince Ring"                                  , "444*" , "Icelandic"       ,
  "Seven-Headed Serpent"                         , "300"  , "Greek"           ,
  "Six Swans"                                    , "451"  , "Unattributed"    ,
  "Snow-Daughter and Fire-Son"                   , "NA"   , "Bukovina"        ,
  "Steadfast Tin-Soldier"                        , "NA"   , "Unattributed"    ,
  "Story of about a Darning-Needle"              , "2029" , "Unattributed"    ,
  "Story of Big Klaus and Little Klaus"          , "NA"   , "Unattributed"    ,
  "Story of King Frost"                          , "480"  , "Russiann"        ,
  "Story of the Emperor's New Clothes"           , "NA"   , "Danish"          ,
  "Swineherd"                                    , "NA"   , "Unattributed"    ,
  "Three Brothers"                               , "NA"   , "Polish"          ,
  "Thumbelina"                                   , "NA"   , "Unattributed"    ,
  "Tinder-Box"                                   , "562"  , "Unattributed"    ,
  "White Duck"                                   , "403"  , "Unattributed"    ,
  "Witch"                                        , "327"  , "Russiann"        ,
  "Witch and Her Servants"                       , "550"  , "Russiann"        ,
  "Witch in the Stone Boat"                      , "403"  , "Icelandic"       ,
  "Wizard King"                                  , "NA"   , "French"
)

blue_fairy_origins <- tibble::tribble(
  ~Title                                               , ~AT        , ~Country         ,
  "Aladdin and the Wonderful Lamp"                     , "561"      , "Arabian Nights" ,
  "Beauty and the Beast"                               , "425C"     , "French"         ,
  "Blue Beard"                                         , "312"      , "French"         ,
  "Bronze Ring"                                        , "NA"       , "MidEast"        ,
  "Cinderella, or the Little Glass Slipper"            , "510A"     , "French"         ,
  "East of the Sun and West of the Moon"               , "425A"     , "Norwegian"      ,
  "Felicia and the Pot of Pinks"                       , "NA"       , "French"         ,
  "Forty Thieves"                                      , "676"      , "Arabian Nights" ,
  "GooseGirl"                                          , "533"      , "German"         ,
  "Hansel and Grettel"                                 , "327A"     , "German"         ,
  "History of Jack Giant-Killer"                       , "300"      , "Scotland"       ,
  "History of Whittington"                             , "1651"     , "Unattributed"   ,
  "History of Jack Giant-Killer"                       , "328"      , "Scotland"       ,
  "Little Red Riding Hood"                             , "333"      , "Unattributed"   ,
  "Little Thumb"                                       , "327B"     , "French"         ,
  "Master Cat, or Puss in Boots"                       , "545B"     , "French"         ,
  "Master-Maid"                                        , "313"      , "Norwegian"      ,
  "Prince Darling"                                     , "NA"       , "French"         ,
  "Prince Hyacinth and the Dear Little Princess"       , "NA"       , "French"         ,
  "Princess on Glass Hill"                             , "530"      , "Norwegian"      ,
  "Red Etin"                                           , "300, 303" , "Scottish"       ,
  "Rumpelstiltzkin"                                    , "500"      , "German"         ,
  "Sleeping Beauty in the Wood"                        , "410"      , "Unattributed"   ,
  "Snow-White and Rose-Red"                            , "426"      , "German"         ,
  "Story of Pretty Goldilocks"                         , "300"      , "French"         ,
  "Story of Prince Ahmed and Fairy Paribanou"          , "NA"       , "Arabian Nights" ,
  "Tale of a Youth Who Set Out to Learn What Fear Was" , "326"      , "German"         ,
  "Terrible Head"                                      , "898"      , "Unattributed"   ,
  "Black Bull of Norroway"                             , "425A"     , "Scottish"       ,
  "Brave Little Tailor"                                , "1640"     , "Unattributed"   ,
  "Toads and Diamonds"                                 , "480"      , "French"         ,
  "Trusty John"                                        , "516"      , "German"         ,
  "Voyage to Lilliput"                                 , "NA"       , "English"        ,
  "Water-Lily. Gold-Spinners"                          , "407"      , "Unattributed"   ,
  "White Cat"                                          , "402"      , "French"         ,
  "Why the Sea is Salt"                                , "565"      , "Norwegian"      ,
  "Wonderful Sheep"                                    , "425"      , "French"         ,
  "Yellow Dwarf"                                       , "NA"       , "French"
)

brown_fairy_origins <- tibble::tribble(
  ~Title                                              , ~AT        , ~Country                ,
  NA                                                  , NA         , " "                     ,
  "Asmund and Signy"                                  , "870B*"    , "Icelandic"             ,
  "Ball-Carrier and the Bad One"                      , "NA"       , "Native American"       ,
  "Bunyip"                                            , "NA"       , "Oceania"               ,
  "Cuning Hare"                                       , "NA"       , "Native American"       ,
  "Elf Maided"                                        , "NA"       , "Lapp"                  ,
  "Enchanted Head"                                    , "444*"     , "MidEast/Central Asian" ,
  "Father Grumbler"                                   , "563"      , "African"               ,
  "Fortune and the Wood-Cutter"                       , "1645B*"   , "MidEast/Central Asian" ,
  "Fox and Lapp"                                      , "1, 2, 73" , "Lapp"                  ,
  "Habogi"                                            , "444*"     , "Icelandic"             ,
  "How Geirald the Coward was Punished"               , "300"      , "Icelandic"             ,
  "How Some Wild Animals Became Tame Ones"            , "NA"       , "Lapp"                  ,
  "How the Ball-Carrier Finished His Task"            , "NA"       , "Native American"       ,
  "How the Little Brother Set Free His Big Brothers"  , "NA"       , "Native American"       ,
  "Husband of Rat's Daughter"                         , "2031C"    , "African"               ,
  "Kisa the Cat"                                      , "NA"       , "Icelandic"             ,
  "Knights of Fish"                                   , "303"      , "Spanish"               ,
  "Lion and Cat"                                      , "NA"       , "Native American"       ,
  "Mermaid and Boy"                                   , "531"      , "Lapp"                  ,
  "Pivi and Kabo"                                     , "NA"       , "Oceania"               ,
  "Prince and Three Fates"                            , "NA"       , "Ancient Egyptian"      ,
  "Rubezahl"                                          , "301A"     , "German"                ,
  "Sacred Mild of Koumongoe"                          , "NA"       , "African"               ,
  "Sister of the Sun"                                 , "NA"       , "Lapp"                  ,
  "Story of the King who Would be Stronger than Fate" , "NA"       , "Indian"                ,
  "Story of Wali Dad the Simple-Hearted"              , "NA"       , "Indian"                ,
  "Story of Yara"                                     , "316"      , "Brazilian"             ,
  "Tale of a Tortoise and a Mischievous Monkey"       , "291"      , "Brazilian"             ,
  "Turtle and his Bride"                              , "433A"     , "Native American"       ,
  "What the Rose Did to the Cypress"                  , "NA"       , "Persian"               ,
  "Which was the Foolishest?"                         , "1406"     , "Icelandic"             ,
  "Wicked Wolverine"                                  , "NA"       , "Native American"
)
